### ISSUE TITLE
Train without target domain label

### ISSUE THREAD

**Issue by Nurungyi** [GiovanniPasq/DA-Faster-RCNN#10]
Can I utilize the DA-Faster R-CNN model when there are no labels in the target domain? I came across a previous query on this topic. In response to that question, it was suggested to add the line cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False to the script, following the cfg_target.INPUT.MIN_SIZE_TRAIN = (600,) instruction.

Given this, I'm considering preparing two datasets:

1) Source domain: All images are labeled using the COCO JSON format. Target domain: 30% of the images have labels (in COCO JSON format), while 70% are unlabeled (no annotation file).

2) Source domain: All images are labeled using the COCO JSON format. Target domain: 100% of the images are unlabeled (no annotation file).
Is it possible to use both dataset configurations (1 and 2) with your API? Moreover, for the unlabeled data, should I still include this information in the COCO JSON (maybe it has no information of bounding box and class)?

**Comment by GiovanniPasq** [comment]
Hello,
the COCO format has main 3 sections: images, categories and annotations. If you want to use this code with your dataset, the target domain must have a coco file and must contains the list of all your images inside the images section of the file. The other two sections (categories and annotations) can be leaved empty or partially filled, in both case the architecture will not use any label for the target domain during its training (you need to include the instruction cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False). 
So, to reply to your questions:

1) the remaining 70% unlabeled images must be include in the same file of the 30% labeled images in the images section but you do not need to add any other information in the categories and annotations sections.
2) you need a coco file with the main three sections and it should contains inside the images section the list of your images and the categories and annotations sections leaved empty.

**Comment by Nurungyi** [comment]
Thank you for your advice. I tried to follow your guide but I got the below error. Can you know why this problem occurs?

cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))
cfg_source.DATASETS.TRAIN = ("source_train",)
cfg_source.DATALOADER.NUM_WORKERS = 2
cfg_source.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml")
cfg_source.SOLVER.IMS_PER_BATCH = 1
cfg_source.SOLVER.BASE_LR = 0.0002
cfg_source.SOLVER.MAX_ITER = 30
cfg_source.INPUT.MIN_SIZE_TRAIN = (600,)
cfg_source.INPUT.MIN_SIZE_TEST = 0
os.makedirs(cfg_source.OUTPUT_DIR, exist_ok=True)
cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 1
model = build_model(cfg_source)

cfg_target = get_cfg()
cfg_target.DATASETS.TRAIN = ("target_train",)
cfg_target.INPUT.MIN_SIZE_TRAIN = (600,)
cfg_target.DATALOADER.NUM_WORKERS = 2
cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False
cfg_target.SOLVER.IMS_PER_BATCH = 1

WARNING [08/16 11:57:57 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
[08/16 11:57:57 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_C4_1x/137257644/model_final_721ade.pkl ...
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 2048) in the checkpoint but (2, 2048) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (2,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 2048) in the checkpoint but (4, 2048) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
Some model parameters or buffers are not found in the checkpoint:
discriminator.reducer.0.weight
discriminator.reducer.2.weight
discriminator.reducer.5.weight
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.box_predictor.cls_score.{bias, weight}
roi_heads.discriminatorProposalDC5.reducer.0.weight
roi_heads.discriminatorProposalDC5.reducer.3.weight
[08/16 11:57:57 d2.data.datasets.coco]: Loaded 135 images in COCO format from /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/source/_annotations.coco.json
[08/16 11:57:57 d2.data.build]: Removed 11 images with no usable annotations. 124 images left.
[08/16 11:57:57 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(600,), max_size=1333, sample_style='choice'), RandomFlip()]
[08/16 11:57:57 d2.data.build]: Using training sampler TrainingSampler
[08/16 11:57:57 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/16 11:57:57 d2.data.common]: Serializing 124 elements to byte tensors and concatenating them all ...
[08/16 11:57:57 d2.data.common]: Serialized dataset takes 0.19 MiB
[08/16 11:57:57 d2.data.datasets.coco]: Loaded 135 images in COCO format from /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/source/_annotations.coco.json
[08/16 11:57:57 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(600,), max_size=1333, sample_style='choice'), RandomFlip()]
[08/16 11:57:57 d2.data.build]: Using training sampler TrainingSampler
[08/16 11:57:57 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/16 11:57:57 d2.data.common]: Serializing 135 elements to byte tensors and concatenating them all ...
[08/16 11:57:57 d2.data.common]: Serialized dataset takes 0.20 MiB
[08/16 11:57:57 detectron2]: Starting training from iteration 0
---------------------------------------------------------------------------
SizeMismatchError                         Traceback (most recent call last)
Cell In[20], line 1
----> 1 do_train(cfg_source,cfg_target,model)

Cell In[11], line 21, in do_train(cfg_source, cfg_target, model, resume)
     18 logger.info("Starting training from iteration {}".format(start_iter))
     20 with EventStorage(start_iter) as storage:
---> 21     for data_source, data_target, iteration in zip(data_loader_source, data_loader_target, range(start_iter, max_iter)):
     22         storage.iter = iteration
     24         loss_dict = model(data_source, False, 0.1)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py:329, in AspectRatioGroupedDataset.__iter__(self)
    328 def __iter__(self):
--> 329     for d in self.dataset:
    330         w, h = d["width"], d["height"]
    331         bucket_id = 0 if w > h else 1

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:633, in _BaseDataLoaderIter.__next__(self)
    630 if self._sampler_iter is None:
    631     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632     self._reset()  # type: ignore[call-arg]
--> 633 data = self._next_data()
    634 self._num_yielded += 1
    635 if self._dataset_kind == _DatasetKind.Iterable and \
    636         self._IterableDataset_len_called is not None and \
    637         self._num_yielded > self._IterableDataset_len_called:

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1345, in _MultiProcessingDataLoaderIter._next_data(self)
   1343 else:
   1344     del self._task_info[idx]
-> 1345     return self._process_data(data)

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1371, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1369 self._try_put_index()
   1370 if isinstance(data, ExceptionWrapper):
-> 1371     data.reraise()
   1372 return data

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/_utils.py:644, in ExceptionWrapper.reraise(self)
    640 except TypeError:
    641     # If the exception takes multiple arguments, don't try to
    642     # instantiate since we don't know how to
    643     raise RuntimeError(msg) from None
--> 644 raise exception

SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/freaktech/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/freaktech/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py", line 296, in __iter__
    yield self.dataset[idx]
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py", line 125, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/dataset_mapper.py", line 155, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/detection_utils.py", line 196, in check_image_size
    raise SizeMismatchError(
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/source/multi_typer.jpg, got (800, 800), expect (0, 0). Please check the width/height in your annotation.

**Comment by Nurungyi** [comment]
cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))
cfg_source.DATASETS.TRAIN = ("source_train",)
cfg_source.DATALOADER.NUM_WORKERS = 2
cfg_source.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml")
cfg_source.SOLVER.IMS_PER_BATCH = 1
cfg_source.SOLVER.BASE_LR = 0.0002
cfg_source.SOLVER.MAX_ITER = 30
cfg_source.INPUT.MIN_SIZE_TRAIN = (600,)
cfg_source.INPUT.MIN_SIZE_TEST = 0
os.makedirs(cfg_source.OUTPUT_DIR, exist_ok=True)
cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 1
model = build_model(cfg_source)

cfg_target = get_cfg()
cfg_target.DATASETS.TRAIN = ("target_train",)
cfg_target.INPUT.MIN_SIZE_TRAIN = (600,)
cfg_target.DATALOADER.NUM_WORKERS = 2
cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False
cfg_target.SOLVER.IMS_PER_BATCH = 1

do_train(cfg_source,cfg_target,model)

WARNING [08/16 12:17:01 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER.
These values will be ignored.
[08/16 12:17:01 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_C4_1x/137257644/model_final_721ade.pkl ...
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 2048) in the checkpoint but (2, 2048) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (2,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 2048) in the checkpoint but (4, 2048) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
Some model parameters or buffers are not found in the checkpoint:
discriminator.reducer.0.weight
discriminator.reducer.2.weight
discriminator.reducer.5.weight
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.box_predictor.cls_score.{bias, weight}
roi_heads.discriminatorProposalDC5.reducer.0.weight
roi_heads.discriminatorProposalDC5.reducer.3.weight
WARNING [08/16 12:17:01 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[08/16 12:17:01 d2.data.datasets.coco]: Loaded 135 images in COCO format from /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/source/_annotations.coco.json
[08/16 12:17:01 d2.data.build]: Removed 0 images with no usable annotations. 135 images left.
[08/16 12:17:01 d2.data.build]: Distribution of instances among all 2 categories:
|  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|
|   closed   | 2710         |    open    | 445          |
|            |              |            |              |
|   total    | 3155         |            |              |
[08/16 12:17:01 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(600,), max_size=1333, sample_style='choice'), RandomFlip()]
[08/16 12:17:01 d2.data.build]: Using training sampler TrainingSampler
[08/16 12:17:01 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/16 12:17:01 d2.data.common]: Serializing 135 elements to byte tensors and concatenating them all ...
[08/16 12:17:01 d2.data.common]: Serialized dataset takes 0.13 MiB
[08/16 12:17:01 d2.data.datasets.coco]: Loaded 135 images in COCO format from /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/target/_annotations.coco.json
[08/16 12:17:01 d2.data.build]: Distribution of instances among all 2 categories:
|  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|
|   closed   | 1186         |    open    | 124          |
|            |              |            |              |
|   total    | 1310         |            |              |
[08/16 12:17:01 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(600,), max_size=1333, sample_style='choice'), RandomFlip()]
[08/16 12:17:01 d2.data.build]: Using training sampler TrainingSampler
[08/16 12:17:01 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/16 12:17:01 d2.data.common]: Serializing 135 elements to byte tensors and concatenating them all ...
[08/16 12:17:01 d2.data.common]: Serialized dataset takes 0.10 MiB
[08/16 12:17:01 detectron2]: Starting training from iteration 0
---------------------------------------------------------------------------
SizeMismatchError                         Traceback (most recent call last)
Cell In[15], line 1
----> 1 do_train(cfg_source,cfg_target,model)

Cell In[13], line 21, in do_train(cfg_source, cfg_target, model, resume)
     18 logger.info("Starting training from iteration {}".format(start_iter))
     20 with EventStorage(start_iter) as storage:
---> 21     for data_source, data_target, iteration in zip(data_loader_source, data_loader_target, range(start_iter, max_iter)):
     22         storage.iter = iteration
     24         loss_dict = model(data_source, False, 0.1)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py:329, in AspectRatioGroupedDataset.__iter__(self)
    328 def __iter__(self):
--> 329     for d in self.dataset:
    330         w, h = d["width"], d["height"]
    331         bucket_id = 0 if w > h else 1

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:633, in _BaseDataLoaderIter.__next__(self)
    630 if self._sampler_iter is None:
    631     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632     self._reset()  # type: ignore[call-arg]
--> 633 data = self._next_data()
    634 self._num_yielded += 1
    635 if self._dataset_kind == _DatasetKind.Iterable and \
    636         self._IterableDataset_len_called is not None and \
    637         self._num_yielded > self._IterableDataset_len_called:

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1345, in _MultiProcessingDataLoaderIter._next_data(self)
   1343 else:
   1344     del self._task_info[idx]
-> 1345     return self._process_data(data)

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1371, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1369 self._try_put_index()
   1370 if isinstance(data, ExceptionWrapper):
-> 1371     data.reraise()
   1372 return data

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/_utils.py:644, in ExceptionWrapper.reraise(self)
    640 except TypeError:
    641     # If the exception takes multiple arguments, don't try to
    642     # instantiate since we don't know how to
    643     raise RuntimeError(msg) from None
--> 644 raise exception

SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/freaktech/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/freaktech/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py", line 296, in __iter__
    yield self.dataset[idx]
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/common.py", line 125, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/dataset_mapper.py", line 155, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/home/freaktech/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/data/detection_utils.py", line 196, in check_image_size
    raise SizeMismatchError(
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image /home/freaktech/Desktop/Seunghyeon/DA_train/window_states/target/abd62.jpg, got (800, 800), expect (0, 0). Please check the width/height in your annotation.

**Comment by GiovanniPasq** [comment]
Hello,
please fix these two problem:
1) cfg_source.SOLVER.MAX_ITER = 30 you are training the model for 30 iterations but the output log during the training is set to 50 as minimum.
NB: iterarions are not epochs, if you want to train the model for 30 epochs you need to calculate the number of iterations as follow:
```
iterations necessary to traing for 1 epoch = len(datasets)/batch
so in your case if your dataset has 135 images and batch is set to 1 you need 135 iterations to achieve 1 epoch (so if you need to do 30 epochs you need to multiply 135 * 30 => 4050 iterations).
If the batch is set to 2 you need 68 iterations to achieve 1 epoch (so if you need to do 30 epochs you need to multiply 68 * 30 => 2040 iterations).
```
2) there is an error in your annotation file as reported in the last row of this error: 
```
abd62.jpg, got (800, 800), expect (0, 0). Please check the width/height in your annotation.
```

**Comment by Nurungyi** [comment]
I fixed the problem. The annotation was problem. Thre dimension of images and annotation size in target data were different. Your code is well-made. Thank you.

**Comment by GiovanniPasq** [comment]
I'm happy to read this message :D
