### ISSUE TITLE
TypeError: GeneralizedRCNN.forward() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Nagamouli41** [GiovanniPasq/DA-Faster-RCNN#17]
i am getting error like this ,please explain why ?
Traceback (most recent call last):
  File "/mnt/d/adaptive_2/uda.py", line 130, in <module>
    do_train(cfg_source,cfg_target,model)
  File "/mnt/d/adaptive_2/uda.py", line 74, in do_train
    loss_dict = model(data_source, False, 0.5)
  File "/home/mouli41/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: GeneralizedRCNN.forward() takes 2 positional arguments but 4 were given

**Comment by Nagamouli41** [comment]
can i use this  with out cuda
